version: '3'
services:
  db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: testtable
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpassword
      MYSQL_ROOT_PASSWORD: rootpassword

    command: mysqld --general-log=1 --general-log-file=/var/lib/mysql/general-query.log

  redis:
    image: redis:6


  go-test:
    image: golang:1.15
    working_dir: "/app"
    volumes:
      - "./scoreserver:/app"
      - "./go-modules:/go/pkg/mod"
    command: "go test ./..."


