version: '3'
services:
  db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: kosenctfx
      MYSQL_USER: kosenctfxuser
      MYSQL_PASSWORD: kosenctfxpassword
      MYSQL_ROOT_PASSWORD: rootpassword

    command: mysqld --general-log=1 --general-log-file=/var/lib/mysql/general-query.log

  redis:
    image: redis:6

  scoreserver:
    build:
      context: scoreserver
    environment:
      DBDSN: 'kosenctfxuser:kosenctfxpassword@tcp(db:3306)/kosenctfx'
      REDIS: 'redis://redis:6379'
      FRONT: 'http://localhost:1/'
      MAIL: 'kosenctf@example.com'
      MAIL_SERVER: 'smtp.gmail.com:587'
      MAIL_PASSWORD: 'XXXXXXXXXXXXXXXXXX'
      ADMIN_WEBHOOK: ''
      SOLVE_WEBHOOK: ''
      TASK_OPEN_WEBHOOK: ''
      ADMIN_TOKEN: "admin"
  
  ui:
    build:
      context: ui2
      dockerfile: Dockerfile.prod

  nginx:
    build:
      context: nginx
      dockerfile: Dockerfile.prod
    ports:
      - "8000:80"

