#!/bin/bash
export DBDSN='kosenctfxuser:kosenctfxpassword@tcp(localhost:13306)/kosenctfx'
export REDIS="rediss://localhost:6379"
export FRONT='http://front.web.localhost:8080'
export MAIL='kosenctf@example.com'
export MAIL_SERVER='smtp.gmail.com:587'
export MAIL_PASSWORD='XXXXXXXXXXXX'
export ADMIN_WEBHOOK="https://discord.com/api/webhooks/XXXXXXXXXXXXXXXXXX/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
export SYSTEM_WEBHOOK="https://discord.com/api/webhooks/XXXXXXXXXXXXXXXXXX/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"

export BUCKET_ENDPOINT="s3.amazonaws.com"
export BUCKET_REGION="ap-northeast-1"
export BUCKET_ACCESS_KEY="XXXXXXXXXXXXXXXXXXXX"
export BUCKET_SECRET_KEY="XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
export BUCKET_NAME="kosenctfx-challenges"
# export BUCKET_INSECURE=1
