#!/bin/bash
export DBDSN='kosenctfxuser:kosenctfxpassword@tcp(localhost:13306)/kosenctfx'
export REDIS="localhost:6379"
export FRONT='http://front.web.localhost:8080'
export MAIL='kosenctf@example.com'
export MAIL_SERVER='smtp.gmail.com:587'
export MAIL_PASSWORD='XXXXXXXXXXXX'

