{
 "title": "New dashboard Copy",
 "time": { "from": "2021-11-04T14:25:47.000Z", "to": "2021-11-04T14:44:07.353Z" },
 "panels": [
  {
   "title": "Solve Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "solve", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Teams",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "number_of_registered_teams" }
   ]
  },
  {
   "title": "registered teams",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 15, "y": 0 },
   "targets": [
    { "expr": "number_of_registered_teams" }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "submissions",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "number_of_submitted_flags" }
   ]
  },
  {
   "title": "valid submissions",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "number_of_valid_flags" }
   ]
  },
  {
   "title": "correct submission rate",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 6, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "number_of_valid_flags / number_of_submitted_flags"
    }
   ]
  },
  {
   "title": "submissions",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 11, "y": 9 },
   "targets": [
    { "expr": "number_of_submitted_flags" },
    { "expr": "number_of_valid_flags" }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "sessions",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "number_of_active_sessions" }
   ]
  },
  {
   "title": "sessions",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 3, "y": 15 },
   "targets": [
    { "expr": "number_of_active_sessions" }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } }
 ]
}