FROM golang:1.15 as builder

WORKDIR /
RUN wget https://github.com/orisano/wayt/releases/download/v0.3.1/wayt_0.3.1_Linux_x86_64.tar.gz && tar xf wayt_0.3.1_Linux_x86_64.tar.gz
RUN go get github.com/cespare/reflex
WORKDIR /scoreserver
